### ISSUE TITLE
Proposal for more complete registration

### ISSUE THREAD

**Issue by francoisPE** [nextcloud/registration#245] opened 2020-10-02 06:53 UTC
Hi,
I would like to propose an evolution of the registration process.
Currently, new account are created based on email + username + pwd
This gives user settings with empty Name, phone number, adress and default language & regional settings
I would propose to add the capability of filling above data when registrating.

###  additional capabilities 
Steps to modify 
1. registration tool management (admin)
   select filling name, phone number, adress, lang, regional 
   3 choices : Not possible, Possible not required, required
 
2. registration process
   a. initial steps kept up to link sent in a mail
   b. when opening the link, on the web page, additional boxes to fill, not only username and pwd.

***
Thanks a lot

**Comment by nickvergessen** [comment] 2021-04-01 11:42
Base work has been laid with #280 and Full name and phone number have been added.
The code for those can not be duplicated to add the other fields.

**Comment by francoisPE** [comment] 2021-04-05 19:46
That's awesome !

**Comment by nickvergessen** [comment] 2023-02-17 13:29
Closing as duplicate of https://github.com/nextcloud/registration/issues/242

**Closed by nickvergessen** 2023-02-17 13:29 UTC
Labels: 1. to develop, enhancement, good first issue, feature: settings ⚙️
