### ISSUE TITLE
Admin approval

### ISSUE THREAD

**Issue by pellaeon** [nextcloud/registration#2] opened 2014-08-31 17:25 UTC
After user enters email (maybe additionally full name), a new pending entry is created, waiting for admin's approval.

After approval, verification email is sent, then the user could create account by clicking the link.

**Comment by tobiasnix** [comment] 2015-08-17 10:16
I just posted a $5 bounty on Bountysource! https://www.bountysource.com/issues/4144723-admin-approval

**Comment by Mr-HeBo** [comment] 2015-08-19 17:55
Yes please! Admin approval would be a very desirable option!!

**Comment by pellaeon** [comment] 2015-09-03 13:04
This is a work in progress on branch `admin-approval`

**Comment by cdamken** [comment] 2015-10-12 23:49
What a I do as workaround is that all new users comes to the "new" group, from there I can manage which should I move to "real" users.

The field with a re

**Comment by ezraholm50** [comment] 2015-10-13 04:34
Same as carlos but i set the storage limit to 1kb so nothing can be
uploaded until "approval". I would love the real deal though! Great work on
the app!

Op di 13 okt. 2015 01:49 schreef Carlos Damken <notifications@github.com>:

> What a I do as workaround is that all new users comes to the "new" group,
> from there I can manage which should I move to "real" users.
>
> The field with a re
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pellaeon/registration/issues/2#issuecomment-147551142>
> .
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by pellaeon** [comment] 2015-11-14 02:45
After discussions at ownCloud conf, decisions are made to change the registration flow, in order to be more straight-forward and simple.

## New registration flow A
1. User clicks the verification link in the email, leads to a account creation form
2. On the form: email (disabled), full name, username, password
3. After submitting the form, user is informed "your account is pending approval"
4. Admin approves
5. An email is sent to the user telling him/her account is created, and provide link to login page

But I guess user will likely forget his/her password by the time admin approves, so here's the alternate flow to prevent that. This flow is also less hacky, becasue flow A needs to write directly to ownCloud's user password.
## New registration flow B
1. User clicks the verification link in the email, leads to a account creation form
2. On the form: email (disabled), full name, username
3. After submitting the form, user is informed "your account is pending approval"
4. Admin approves
5. An email is sent to the user telling him/her the request is approved, and provide a link to to the password setting form
6. On the form: email (disabled), full name (disabled), username (disabled), password
7. User submits the form, gets logged in directly

@cdamken @tobiasnix What do you all think?

**Comment by pellaeon** [comment] 2015-11-14 02:50
Subtasks:

- [ ] Admin approval interface, integrated with ownCloud's user administration page, partially completed, see `admin-approval` branch
- [ ] New database schema is needed to accomadate full name and password (flow A), this entry will be deleted once a new account is created

**Comment by tobiasnix** [comment] 2015-11-15 12:17
As there is a native password reset feature in owncloud i am voting for flow A. Its one step less for users who remember their password.

**Comment by ezraholm50** [comment] 2015-12-19 08:39
Would also go for A although B seems workable. You could include the reset password link in the email maybe?

Another option would be to add the password to the registration email, but I find it quite insecure when sites do that, never know for sure if someone's mail server is using ssl/tls.

The workaround still works for me, user group validation has no apps, 1kb storage, they get the notification upon login that their storage is full. Only problem is that they have access to the file sharing, which can't be disabled for usergroups. Which in turn makes the validation group able to view registered users, of what I can think would be a not wanted problem for some OwnCloud hosts.

Could you give me an update how?

Regards

**Comment by pellaeon** [comment] 2015-12-31 04:48
I thought of a new simplified flow:

On first form, user inputs:
- email
- desired username
- display name
- password

Validation email is sent to the user, notification is sent to the admin.

1. If the user validates email before admin decides, a message is shown to user "email validated, pending admin approval". When the admin approves/denies an additional email is sent to user.

2. If the user validates email after admin approves, he is shown "email validated, logging you in" and redirected to files app.

3. If admin denies before user validates, when the admin denies, user is notified. Admin can also drop the signup directly, user won't be notified.

4. If admin approval feature is turned off, the flow is same as 2

**Comment by intresrl** [comment] 2016-01-27 15:32
A (less 'burocracy'). I agree with @tobiasnix .

**Comment by georgygoshin** [comment] 2017-02-27 22:50
Can't find this feature (admin approve required) in the latest nextcloud, how to get it on?

**Comment by pellaeon** [comment] 2017-02-28 06:02
@georgygoshin It's still a work in progress.

**Comment by jasonehines** [comment] 2017-05-12 13:26
I'd also like this feature

**Comment by githubos1** [comment] 2017-05-17 22:32
May I suggest that in the process of approval by admin, the registered users e-mail will automatically be added to the user database ?? currently that seems not the case... all users e-mail settings are empty...

Regards,
Oliver

**Comment by Ich5003** [comment] 2018-01-14 12:52
Are there any updates on this?

**Comment by derBobby** [comment] 2018-03-08 21:53
Also interested!

**Comment by lordmampf** [comment] 2018-03-11 16:52
I'm working on it. But I'm currently really busy.
So if you are a dev and you want to help:
https://github.com/lordmampf/registration

**Comment by jgrete** [comment] 2018-03-29 17:26
I've the problem that a newly created user does not show up in the user list. The entry is invisible but the member count on the left side for the "registered" group is correct. An email was sent to the admin but I've no idea how to approve the new user. Looks very strange to me...

**Comment by cdamken** [comment] 2018-03-29 19:13
> I'm working on it. But I'm currently really busy.
> So if you are a dev and you want to help:
> https://github.com/lordmampf/registration

I can help to test it, just let me know when you have some advances and I can help.

**Comment by borekon** [comment] 2018-04-07 19:48
So, the option can be checked but i can't see where to approve new users

**Comment by MarcelAlers** [comment] 2018-04-26 17:13
I'm also interested in that feature.

@lordmampf I can help you. I've just downloaded the code.

**Comment by lordmampf** [comment] 2018-04-27 22:38
@MarcelAlers 

Thanks for your pr on my fork ;)
Is Admin approval working so far on your installation?

**Comment by andreadelutti** [comment] 2018-11-21 17:56
I am also interested in this feature... Thanks

**Comment by Mardiie** [comment] 2019-05-03 23:47
If you ask me this needs to be in before this is usable on the open web without workarounds like a group with no storage space!

**Comment by intika** [comment] 2019-11-26 21:11
On the current implementation there is no way to view users that had not confirmed their email (other than the database) 

It would be nice if pending registration would be displayed on the config page... 

Thanks :)

**Comment by nickvergessen** [comment] 2020-11-17 19:48
> On the current implementation there is no way to view pending users that had not confirmed their email (other than the database)
> It would be nice if pending registration would be displayed on the config page.

Can you create a new issue for that?
I would close this one here, because admin approval now already exists.

**Closed by nickvergessen** 2020-11-17 19:48 UTC
Labels: 1. to develop, enhancement

**Comment by mk3-v8** [comment] 2023-05-31 06:04
Can we have a field where we can assign approval by specific groups such as "Help Desk" in our case so they can manage the account creation process not only the administrator?
