### ISSUE TITLE
Internal Server Error after requesting verification link

### ISSUE THREAD

**Issue by gamernjs** [nextcloud/registration#267] opened 2021-01-24 21:18 UTC
I'm getting an Internal Server Error after requesting a verification link. It happens on the local network and over the internet.

<img width="812" alt="Screen Shot 2021-01-24 at 2 17 32 PM" src="https://user-images.githubusercontent.com/13448432/105643747-f244fe80-5e4e-11eb-9659-0425c5ed54d0.png">

**Comment by nickvergessen** [comment] 2021-01-24 21:20
Please check the server logs as it says.
You should find an error there

**Comment by nickvergessen** [comment] 2021-02-06 10:35
Closing due to the lack of feedback

**Comment by xxxcrow** [comment] 2021-02-20 21:56
`[index] Error: Swift_TransportException: Connection could not be established with host 127.0.0.1 :stream_socket_client(): unable to connect to 127.0.0.1:25 (Connection refused) at <<closure>>

 0. <<closure>>
    Swift_Transport_StreamBuffer->{closure}("*** sensitive parameters replaced ***")
 1. /snap/nextcloud/26131/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php line 272
    stream_socket_client("127.0.0.1:25", 111, "Connection refused", 10, 4, null)
 2. /snap/nextcloud/26131/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php line 58
    Swift_Transport_StreamBuffer->establishSocketConnection()
 3. /snap/nextcloud/26131/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 143
    Swift_Transport_StreamBuffer->initialize({0: "And 3 more  ... 1})
 4. /snap/nextcloud/26131/htdocs/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php line 65
    Swift_Transport_AbstractSmtpTransport->start()
 5. /snap/nextcloud/26131/htdocs/lib/private/Mail/Mailer.php line 204
    Swift_Mailer->send(Swift_Message {}, [])
 6. /var/snap/nextcloud/26131/nextcloud/extra-apps/registration/lib/Service/MailService.php line 132
    OC\Mail\Mailer->send(OC\Mail\Message {})
 7. /var/snap/nextcloud/26131/nextcloud/extra-apps/registration/lib/Controller/RegisterController.php line 143
    OCA\Registration\Service\MailService->sendTokenByMail(OCA\Registration\Db\Registration {id: 1})
 8. /snap/nextcloud/26131/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 169
    OCA\Registration\Controller\RegisterController->submitEmailForm("kyzkazk@gmail.com")
 9. /snap/nextcloud/26131/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Registration ... {}, "submitEmailForm")
10. /snap/nextcloud/26131/htdocs/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Registration ... {}, "submitEmailForm")
11. /snap/nextcloud/26131/htdocs/lib/private/Route/Router.php line 309
    OC\AppFramework\App::main("OCA\\Registrati ... r", "submitEmailForm", OC\AppFramework\ ... {}, {_route: "regist ... "})
12. /snap/nextcloud/26131/htdocs/lib/base.php line 1008
    OC\Route\Router->match("/apps/registration/")
13. /snap/nextcloud/26131/htdocs/index.php line 37
    OC::handleRequest()

POST /index.php/apps/registration/
from 192.168.1.1 at 2021-02-20T21:51:15+00:00`

**Comment by xxxcrow** [comment] 2021-02-20 22:14
the email account has not been set up in the "Basic settings"

**Comment by nickvergessen** [comment] 2021-02-20 22:15
Yeah fix it 🤷‍♂️
Can't sent emails without emails being configured?

**Comment by xxxcrow** [comment] 2021-02-20 23:06
@nickvergessen yeah, i know, just answering about the issue because it was closed due inactivity 👌

**Comment by gamernjs** [comment] 2021-02-20 23:13
@nickvergessen I realized my mistake shortly after asking my question and forgot to delete my issue. Thank you I need to setup a email server for my domain.

**Comment by nickvergessen** [comment] 2021-02-22 18:45
Okay when I remove all email configuration I can reproduce the exception. Will make it a beautiful error.

**Comment by nickvergessen** [comment] 2021-02-22 18:57
Fix is in https://github.com/nextcloud/registration/pull/274

**Comment by xxxcrow** [comment] 2021-02-22 20:18
@nickvergessen

**Closed** 2021-02-23 07:25 UTC
Labels: needs info
