### ISSUE TITLE
When trying to register with weak password no hint is shown

### ISSUE THREAD

**Issue by XXDoMi77** [nextcloud/registration#257] opened 2020-11-17 11:13 UTC
### Steps to reproduce
1. Try to register with weak password

### Expected behaviour
Above the password input, text should appear that says:
"Password needs to contain at least one uppercase letter"
"Password needs to contain at least one number"
"Password needs to conatin at least one special character '#*/@' "
etc.

### Actual behaviour
You click the button and nothing happens

### Server configuration
**Operating system:** Ubuntu Server x64 arch kernel Raspberry Pi 4 8GB
Linux 5.4.0-1022-raspi aarch64

**Web server:** nginx 

**Database:** mariadb/ mysql 10.3.25

**PHP version:** 7.4.3 Memory limit: 4GB

**Nextcloud version:** 20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated form 19.0.4

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/latest.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.2
  - admin_audit: 1.10.0
  - announcementcenter: 4.0.0
  - apporder: 0.11.0
  - audioplayer: 2.12.0
  - audioplayer_editor: 0.3.0
  - breezedark: 20.0.1
  - bruteforcesettings: 2.0.1
  - camerarawpreviews: 0.7.9
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - customproperties: 1.0.1
  - dav: 1.16.0
  - duplicatefinder: 0.0.4
  - extract: 1.2.5
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_3d: 0.3.3
  - files_downloadactivity: 1.9.0
  - files_linkeditor: 1.1.2
  - files_markdown: 2.3.1
  - files_pdfviewer: 2.0.1
  - files_photospheres: 1.20.0
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trackdownloads: 1.9.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - forms: 2.0.4
  - group_everyone: 0.1.6
  - impersonate: 1.7.0
  - issuetemplate: 0.7.0
  - login_notes: 0.3.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - metadata: 0.12.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - passwords: 2020.11.0
  - photos: 1.2.0
  - polls: 1.5.7
  - previewgenerator: 3.0.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - quota_warning: 1.9.1
  - registration: 0.5.1
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - side_menu: 1.20.1
  - support: 1.3.0
  - survey_client: 1.8.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_usage_report: 1.4.2
  - video_converter: 0.1.5
  - viewer: 1.4.0
  - workflowengine: 2.2.0
Disabled:
  - checksum
  - contacts
  - dashboard
  - encryption
  - files_external
  - firstrunwizard
  - recommendations
  - sharebymail
  - sharingpath
  - systemtags
  - user_ldap
  - user_status
  - weather_status
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'oclpxk8wo1ul',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'dominikscloud.com',
  ),
  'datadirectory' => '/mnt/data/nextcloud-data',
  'dbtype' => 'mysql',
  'version' => '20.0.1.1',
  'overwrite.cli.url' => 'https://dominikscloud.com',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'no-reply',
  'mail_domain' => 'dominikscloud.com',
  'mail_smtphost' => '',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'app_install_overwrite' => 
  array (
    0 => 'whiteboard',
    1 => 'registration',
  ),
  'maintenance' => false,
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'support@dominikscloud.com',
  'mail_smtppassword' => '',
  'simpleSignUpLink.shown' => false,
  'updater.release.channel' => 'stable',
  'htaccess.RewriteBase' => '/',
  'session_lifetime' => 43200,
  'session_keepalive' => false,
  'remember_login_cookie_lifetime' => 43200,
  'loglevel' => 2,
);
```

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav, Samba

</details>

### Client configuration
**Browser:** All browsers

**Operating system:** All platforms

#### Web server error log
<details>
<summary>Web server error log</summary>

```
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"XHcKBNgcTZBWOJKjWCpO","level":3,"time":"2020-11-17T11:06:49+00:00","remoteAddr":"77.75.207.36","user":"--","app":"PHP","method":"POST","url":"/apps/registration/register/e6ikPNsfFbMkiebPRESGrGMostaAHjsN/Ta25J9zKB3","message":{"Exception":"Error","Message":"Undefined index: token at /usr/share/nginx/nextcloud/apps/registration/templates/form/user.php#6","Code":0,"Trace":[{"file":"/usr/share/nginx/nextcloud/apps/registration/templates/form/user.php","line":6,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/usr/share/nginx/nextcloud/lib/private/Template/Base.php","line":178,"args":["/usr/share/nginx/nextcloud/apps/registration/templates/form/user.php"],"function":"include"},{"file":"/usr/share/nginx/nextcloud/lib/private/Template/Base.php","line":150,"function":"load","class":"OC\\Template\\Base","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/legacy/OC_Template.php","line":180,"function":"fetchPage","class":"OC\\Template\\Base","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php","line":210,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":123,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/share/nginx/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/share/nginx/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/share/nginx/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 Edg/86.0.622.69","version":"20.0.1.1","id":"5fb3aecac3795"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment] 2020-11-17 18:38
Duplicate of #42

**Closed by nickvergessen** 2020-11-17 18:38 UTC
