### ISSUE TITLE
Cannot save configuration

### ISSUE THREAD

**Issue by pellaeon** [nextcloud/registration#44] opened 2016-07-08 10:04 UTC
Reports on app store says configuration cannot be saved, investigating.

**Comment by janmashat** [comment] 2016-08-30 13:23
I can confirm that trying to change the Default group, for example, throws this error:
```
Request URL: https://owncloud.local/index.php/apps/registration/settings
Request Method: POST
Status Code: 404 Not Found
Remote Address: 127.0.0.1:443
```

**Comment by janmashat** [comment] 2016-09-01 08:32
The workaround I used is to set the values directly in the db...

`mysql> insert into oc_appconfig ( appid, configkey, configvalue ) values ( "registration", "allowed_domains", "example.com" );`

**Comment by jdevstart** [comment] 2016-12-23 19:53
Excuse my ignorance since I'm still new to this but when I type your command above, do I leave it as is or do I modify it to actually use the domain I want to use. 

Example:
mysql> insert into oc_appconfig ( appid, configkey, configvalue ) values ( "registration", "allowed_domains", "**testdomain**.com" );

**Comment by janmashat** [comment] 2016-12-24 08:48
Yes, you should modify it.

**Comment by jdevstart** [comment] 2016-12-28 15:14
Adding the values directly in the db didn't seem to work for me.  I never received an e-mail in my inbox to confirm the registration but I think it may be tied in with this issue.

https://github.com/pellaeon/registration/issues/51

**Comment by jasonbayton** [comment] 2017-01-04 21:27
Adding my voice here, installed on Nextcloud 11 and am unable to save the default group, it resets on page refresh.

**Comment by thetre97** [comment] 2017-01-22 21:13
yes - I have a similar issue, the default group does not save...

**Comment by Grantmu** [comment] 2017-01-24 21:18
is there an edit on the APP files that i can do to get this working. or any other work around

**Comment by Grantmu** [comment] 2017-01-25 15:22
found something that sort of works, allows for the completion of an account but still deos not allocate the account to the correct group. So I created the group I want to place the users in, Then in the admin section I enabled the program, rebooted the application (server), then back to the admin section and enabled this to only work with the specific group, the one i created for all these users. Now the creation of the new user completes but still does not filler the new user based on the Email domain address. It also does not seem to matter that I disable the ONLY for THIS GROUP function, the application still seems to work. 

Looking into the code and if I find a solution I will post it here. I think it is trying to update a field in the DB that is not there anymore. 

Using nextcloud 10.0.0.1

Grantmu

**Comment by nashbrydges** [comment] 2017-02-22 18:41
I had the same issue and here is what I did to get a workaround...

**Manually Add Allowed Domains In DB:**
`insert into oc_appconfig ( appid, configkey, configvalue ) values ( "registration", "allowed_domains", "list your domains here separated by a semicolon" );`

**Manually Add A Default Group In DB:**
`insert into oc_appconfig ( appid, configkey, configvalue ) values ( "registration", "registered_user_group", "New" );`

In this case I added the default "New" group that all new users would be assigned to. I then went to file access control and added this "New" group so no one would have access until I added them to the correct group following registration. The only caveat to this is that when they complete registration, they are automatically loging in which is not allowed because of my chosen default block action. That's something I can live with a prepare users to see when they register.

The next thing was that I noticed when you tried to select anything on the Admin page or enter anything into the allowed domains list, everything would change back to their previous settings (it would overwrite what I manually entered in the db). I instead found the admin.php page in the /apps/registration/templates/ folder and made the following changes to the PHP code...

```
<?php
script('registration', 'settings');
?>
<form id="registration" class="section">
	<h2><?php p($l->t('Registration')); ?></h2>
	<p>
	<label for="registered_user_group"><?php p($l->t('Default group that all registered users belong - DISABLED - Set to New by default by Sylvain')); ?></label>
	<select disabled id="registered_user_group" name="registered_user_group">
		<option value="New" <?php echo $_['current'] === 'New' ? 'selected="selected"' : ''; ?>><?php p($l->t('New')); ?></option>
<?php
foreach ( $_['groups'] as $group ) {
	$selected = $_['current'] === $group ? 'selected="selected"' : '';
	echo '<option value="'.$group.'" '.$selected.'>'.$group.'</option>';
}
?>
	</select>
	</p>
	<p>
	<label for="allowed_domains"><?php p($l->t('Allowed mail address domains for registration')); ?></label>
	<input disabled type="text" id="allowed_domains" name="allowed_domains" value=<?php p($_['allowed']);?>>
	</p>
	<p>
	<em><?php p($l->t('Enter a semicolon-separated list of allowed domains. Example: owncloud.com;github.com'));?> 
    <p>To enter new allowed domains, see text file documentation for SQL query.</p>
</em>
	</p>

</form>
```

What this does is disable the 2 fields in the admin form and forces the values I manually entered in the db to remain unchanged. If you make these changes, the fields can't be edited within the form and users can proceed and register as per normal (with the final error message because I chose to deny access for New users).

I tested this with domains that are not in the allowed domains list and they appropriately got the message that they were not allowed. The problem was that it listed the allowed domains. I didn't want that list to be made public, so instead, I also changed the domains.php file that is in the same directory as the admin.php file and made the following edits...

```
<?php
\OCP\Util::addStyle('registration', 'style');
?>
<ul class="error-wide">
	<li class='error'><?php p($l->t('Your email domain is not on the allowed domains list. If you believe you are receiving this message in error, please contact the site administrator at info@jpslconsulting.ca.')); ?>
	</li>
</ul>
```

This will now only tell the user that they are NOT on the allowed list, but won't tell them what that list actually contains.

Not perfect but gets me to a working solution with minimal work. Hope this can help someone.

**Comment by nashbrydges** [comment] 2017-02-22 18:44
If you need to change the list of allowed domains in the MYSQL db, you can run this update query...

`update oc_appconfig set configvalue = "your new list of domains separated by semicolons" where appid="registration" and configkey = "allowed_domains";`

**Comment by pierreozoux** [comment] 2017-10-02 20:57
I didn't see the issue any more, I think it is fixed, can you confirm?

**Comment by danielepercivaldi** [comment] 2017-12-10 10:20
@pierreozoux , issue still exists in 0.3.1.

**Comment by pellaeon** [comment] 2017-12-21 10:18
@danielepercivaldi Could you log and show me the HTTP request and response that was made? You can find it in the browser developer console. Find request for the URL `/index.php/apps/registration/settings`

**Comment by danielepercivaldi** [comment] 2017-12-26 11:32
@pellaeon here you are:
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by pellaeon** [comment] 2017-12-26 11:48
@danielepercivaldi It is normal that the settings folder does not exist, the web server settings should rewrite all urls to `index.php` , the path routing will be handled by Nextcloud.

Can you also post relevant lines in nextcloud/owncloud logs? and also web server logs?

If you use Apache HTTPd, please make sure it will read configs from `.htaccess` files. If you use Nginx, please configure according to the [documentation](https://docs.nextcloud.com/server/12/admin_manual/installation/nginx.html).

**Comment by danielepercivaldi** [comment] 2017-12-26 13:21
@pellaeon Well, no relevant log in apache and owncloud. All owncloud folders belongs to www-data (user and group) so the access to any .htaccess is granted.
Find attached a more detailed console log in reference to saving action.
[1514294159418.log](https://github.com/pellaeon/registration/files/1587369/1514294159418.log)

**Comment by nickvergessen** [comment] 2020-07-10 08:03
Seems to work in newest version

**Closed by nickvergessen** 2020-07-10 08:03 UTC
