### ISSUE TITLE
Permit configuration to Template used to generate Verification email 

### ISSUE THREAD

**Issue by Daksol** [nextcloud/registration#243] opened 2020-09-17 13:58 UTC
Feature request - not seen this in open or closed issues.

We want to provide info to new users via the text which appears in the Verification email.
For instance we would want to include an information text just after the "Welcome" line which would include info about choice of userid format, and refer new users to Help resources. We would want to edit that text via the existing Admin interface for the Registration App (eg where the "group to add new users to" is specifed).

Thanks

#### Existing format for the Verification email
```
Welcome to Nextcloud community!

Click the following link to confirm and activate your new account:
https://<server url>/u/activate-account/<onceoff_activation_code>

If the above link is not clickable, try copying and pasting it into the address bar of your web browser.
```

**Comment by nickvergessen** [comment] 2020-11-17 19:49
Duplicate of #142

**Closed by nickvergessen** 2020-11-17 19:49 UTC
Labels: enhancement, feature: settings ⚙️

**Comment by Daksol** [comment] 2021-01-05 22:09
Thanks for getting this new feature put live. This is going to eliminate a lot of otherwise unproductive admin effort.
