### ISSUE TITLE
Registration-Button not displayed in custom color set in Theming app

### ISSUE THREAD

**Issue by mrbutcher93** [nextcloud/registration#206] opened 2020-04-29 08:14 UTC
### Steps to reproduce
1. Activate Registration App
2. Select custom color in Theming
3. Go to login page

### Expected behaviour
Registration Button in custom color of Theming App

### Actual behaviour
Registration Button in standard color blue/white

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** mysql 5.7.29

**PHP version:** 7.3.17

**Nextcloud version:** 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 17

**Where did you install Nextcloud from:** Snap

**Comment by nickvergessen** [comment] 2020-07-10 07:52
Duplicate of #68

**Closed by nickvergessen** 2020-07-10 07:52 UTC
Labels: 1. to develop, bug, design
