### ISSUE TITLE
Text color of register button

### ISSUE THREAD

**Issue by sualko** [nextcloud/registration#347] opened 2021-10-18 10:43 UTC
### Steps to reproduce
1. Enable app
2. Change theme color to something dark
3. Go to login page

### Expected behaviour
Everything looks nice :smile: 

### Actual behaviour
Depending on your theme color, the text color of the registration button is different to all other buttons.

![2021-10-18 12 19 301811b4d84098](https://user-images.githubusercontent.com/2974196/137716055-28193332-8b06-400c-b630-744821123e2f.png)

The easiest solution would be to remove the explicit color, since the primary color variable seams still to be black.

![2021-10-18 12 19 50 b80c415bb227](https://user-images.githubusercontent.com/2974196/137716140-05932f8b-854c-483f-8e0d-4b704d916cc3.png)

### Server configuration
**Nextcloud version:** (see Nextcloud admin page) 22

**Comment by sualko** [comment] 2022-01-07 12:15
> The problem is the CSS variables are not loaded when a guest in bright mode is on the login page.

I do not understand this, since If I remove the explicit color, everything works fine. I removed the color and loaded the login page in a private window.

**Comment by JordanDIG** [comment] 2022-03-09 04:54
I have exactly the same problem.
I'm just waiting for a correction from Nextcloud

**Comment by JordanDIG** [comment] 2022-03-09 04:54
In nextcloud 23 ^^

**Comment by JordanDIG** [comment] 2022-03-09 05:01
> ### Steps to reproduce
> 1. Enable app
> 2. Change theme color to something dark
> 3. Go to login page
> 
> ### Expected behaviour
> Everything looks nice 😄
> 
> ### Actual behaviour
> Depending on your theme color, the text color of the registration button is different to all other buttons.
> 
> ![2021-10-18 12 19 301811b4d84098](https://user-images.githubusercontent.com/2974196/137716055-28193332-8b06-400c-b630-744821123e2f.png)
> 
> The easiest solution would be to remove the explicit color, since the primary color variable seams still to be black.
> 
> ![2021-10-18 12 19 50 b80c415bb227](https://user-images.githubusercontent.com/2974196/137716140-05932f8b-854c-483f-8e0d-4b704d916cc3.png)
> 
> ### Server configuration
> **Nextcloud version:** (see Nextcloud admin page) 22

Except that under this version (nextcloud 23) changing the color by the default one does not solve the problem :/

**Comment by JordanDIG** [comment] 2022-03-09 17:45
> Part 1: fixed with [nextcloud/server#31500](https://github.com/nextcloud/server/pull/31500) Part 2: Remove handling in
> 
> https://github.com/nextcloud/registration/blob/d999dcb8af2c5842eb5799159aee9fd0cea3bcbb/css/register-button.css#L1-L9

When will this be fixed in an update?

**Comment by JordanDIG** [comment] 2022-03-14 06:48
@nickvergessen

**Comment by JordanDIG** [comment] 2022-03-14 10:07
Okay thanks

**Comment by JordanDIG** [comment] 2022-04-06 21:24
Hello,
I just installed the application on my instance under nextcloud 24 and the text color of the signup button is black...

> As it involves a server fix which is not going to be backported it might take until Nextcloud 24.

**Comment by JordanDIG** [comment] 2022-04-10 09:52
Cc @nickvergessen

**Comment by nickvergessen** [comment] 2022-04-11 11:37
Hey @JordanDIG , I really appreciate how interested you are in the Nextcloud ecosystem and this app. I notice you ping me on issues and I would like to ask you to not do this to me or other people. We have a high workload, so we have to prioritize and these pings cause much distraction and stress. Thanks!

**Comment by nickvergessen** [comment] 2022-04-11 11:45
![Bildschirmfoto von 2022-04-11 13-43-13](https://user-images.githubusercontent.com/213943/162732600-7f4f8ee1-adaa-4d24-a6a8-8e5ab5c32dd2.png)

As written before it's working with master of this app and upcoming 24 release.
So please be patient for that release.

If it still happens for you after 24 is out and you updated the server and the app, feel free to create a new issue with all the necessary information, especially theming color, dark/bright mode of your OS, browser, ....

**Closed by nickvergessen** 2022-04-11 11:45 UTC
Labels: bug

**Comment by ressit** [comment] 2022-05-09 23:18
In nc before release 24, consider to add the "custom css" app and adjust the color to your theme:
```
#alternative-logins.alternative-logins .button.register-button {
  background-color: #150080;
  color: white !important;
}
```

**Comment by meyerchak** [comment] 2022-05-30 00:50
Nextcloud 24.0.1
PHP 8.1
PostgreSQL

Thank you for the great app!

I was hoping updating to v24 would fix the problem but the theme color is still not showing. i have tried occ maintenance:theme:update with no change.

Any ideas please?

Steps to reproduce:
    1. Enable app
    2. Go to login page
![registration not showing theme color](https://user-images.githubusercontent.com/8461530/170898679-de6a912d-1530-420a-9be9-3628d5af629b.png)

Thank you for your time!

**Comment by kawasumi2019** [comment] 2022-06-05 16:37
1. Install app "Custom CSS"
2. Enter the following this CSS for bottom of Theming settings:
```
#alternative-logins.alternative-logins .button.register-button, .alternative-logins a.button { 
    border: 1px solid <color-code>; 
    color: var(--color-primary-text) !important;
    background-color: <color-code>;
} 
#alternative-logins.alternative-logins .button.register-button:focus, .alternative-logins a.button:focus { 
    border: 2px solid <color-code>; 
    color: var(--color-primary-text) !important;
    background-color: <color-code>;
    background-image: linear-gradient(40deg, <color-code-bottomleft> 0%, <color-code-topright> 100%); 
    background-position: initial; 
    padding: 11px 19px;
}
```
3. If you want to set different parameters for the two buttons, separate them as follows:
```
#alternative-logins.alternative-logins .button.register-button {}
 .alternative-logins a.button {}
```

**Comment by meyerchak** [comment] 2022-06-06 01:21
Dear Kawasumi2019

Thank you for the reply

I tried the code below, no luck. I also tried to add my color code where it says color-code, no luck.

I tried removing the #, no luck.

Is there any more advise you can give me?

Thank you

bill

William Meyerchak
(310) 562-6605
***@***.***

**Comment by ressit** [comment] 2022-06-06 11:14
According to my personal CSS expert, basically the :hover selector seems to be missing.

```
#alternative-logins.alternative-logins .button.register-button {
  background-color: #150080;
  color: var(--color-primary-text) !important;
} 

#alternative-logins.alternative-logins .button.register-button:focus, 
#alternative-logins.alternative-logins .button.register-button:hover,
.alternative-logins a.button:focus,
.alternative-logins a.button:hover{
  background-image: linear-gradient(40deg, #150080 0%, #2600e6 100%);
}

```
The linear-gradient starts with your background-color at 0%.
The background-color at 100% could be calculated using the nice calculator from
https://hslpicker.com/
Enter your background-color value and add 20 to the saturation (3. row from top).

**Comment by meyerchak** [comment] 2022-06-06 23:59
Thank you!

Worked perfectly.  Thank you.  Thank you for letting me know about adding 20 to the color.
Looks great. 
Your expert is really good!

Best

Bill



William Meyerchak
(310) 562-6605
***@***.***

**Comment by ressit** [comment] 2023-01-22 01:17
After upgrade from R23.0.12 to R24.0.9 the issue seems to be still present. I added the adjusted solution from my personal CSS expert to https://github.com/nextcloud/server/issues/31657#issuecomment-1399370826 .
