### ISSUE TITLE
Send welcome email automatically once admin activates the user

### ISSUE THREAD

**Issue by mkriegl** [nextcloud/registration#167] opened 2019-02-28 16:31 UTC
I acivated admin aproval. During registaration I received the e-mail to wait and the admin for aproval. I could not find any aproval function in nextcloud and did not receive any info.
When I try again, I get the error, that the user is already registered, but I cannot find it in the user list.

**Comment by mkriegl** [comment] 2019-02-28 16:45
Oh, I just found it. The new user is listed in the deactivated users. There ist only on issue left. While activating the user the welcome mail has to be send manually

**Comment by nickvergessen** [comment] 2020-07-10 07:25
Duplicate of #137

**Closed by nickvergessen** 2020-07-10 07:25 UTC
Labels: 1. to develop, enhancement, feature: settings ⚙️
